// GENERATED by scripts/embed-image-sizes.mjs — do not edit.
//
// The intrinsic pixel size of every screenshot under `public/`, read from the
// PNG headers, plus whether `optimise-screenshots.mjs` has written a `.webp`
// beside it. Regenerated by `npm run build`.
//
// Consumed by the `Shot` and `Annotated` components so that no `<img>` on the
// site is written without a width and a height, and so the WebP is offered
// only when it exists.

export interface ImageAsset {
  width: number;
  height: number;
  webp: boolean;
}

export const IMAGE_SIZES: Record<string, ImageAsset | undefined> = {
  "/screens/cli-auto.png": { width: 1696, height: 728, webp: true },
  "/screens/cli-baseline.png": { width: 1696, height: 728, webp: true },
  "/screens/cli-compare.png": { width: 2260, height: 854, webp: true },
  "/screens/cli-doctor.png": { width: 1696, height: 896, webp: true },
  "/screens/report-clean-dark.png": { width: 2260, height: 1126, webp: true },
  "/screens/report-clean-light.png": { width: 2260, height: 1126, webp: true },
  "/screens/report-explain-findings.png": { width: 2244, height: 1524, webp: true },
  "/screens/report-explain-injection.png": { width: 2244, height: 514, webp: true },
  "/screens/report-fidelity-frame.png": { width: 2244, height: 1634, webp: true },
  "/screens/report-flagged-dark.png": { width: 2260, height: 1128, webp: true },
  "/screens/report-flagged-light.png": { width: 2260, height: 1128, webp: true },
  "/screens/report-fullpage-frames.png": { width: 2260, height: 1026, webp: true },
  "/screens/report-lightbox.png": { width: 2880, height: 2000, webp: true },
  "/screens/report-overview-dark.png": { width: 2880, height: 4552, webp: true },
  "/screens/report-overview-light.png": { width: 2880, height: 4552, webp: true },
  "/screens/report-summary-dark.png": { width: 2392, height: 822, webp: true },
  "/screens/report-summary-light.png": { width: 2392, height: 822, webp: true },
  "/screens/report-target-frame.png": { width: 2244, height: 1634, webp: true },
  "/screens/report-target-masthead.png": { width: 2388, height: 456, webp: true },
  "/cases/case-01/bose-full-page-diff.png": { width: 415, height: 1600, webp: true },
  "/cases/case-01/build.png": { width: 415, height: 1600, webp: true },
  "/cases/case-01/design.png": { width: 438, height: 1600, webp: true },
  "/cases/case-02/s2/norma-hero-diff.png": { width: 1440, height: 1000, webp: true },
  "/cases/case-02/s5/articles-index-diff.png": { width: 1440, height: 1000, webp: true },
};
