-- Sessions, both sign-in methods, and the outbound-email budget behind magic
-- links — FUTURENORMA §4 Step 6, PATHWAYS Pathway 5 / §10.7 5A.
--
-- Until now the only identities in the product were an API key (a pipeline, not
-- a person) and a share token (a capability for one run). `users`, `memberships`
-- and `orgs` have existed since 001 and nothing has ever logged in.
--
-- Everything here arrives together, because it is one mechanism:
--
--   login_identities  how a person proves they are that row in `users`
--   sessions          the proof, held in a cookie, revocable and expiring
--   login_tokens      a magic link: short-lived, single-use, hashed at rest
--   invitations       the only way a person joins an organization
--   owner_claims      the only way an organization gets its first human
--   orgs.owner_user_id  the ownership invariant PATHWAYS §10.7 5A.5 requires
--   auth_throttle     the ceilings that make an unauthenticated send endpoint
--                     safe to expose at all
--   auth_events       the redacted audit log for all of it
--
-- The reason the throttle is in this migration rather than a later one: a magic
-- link lets **anyone on the internet make us send mail to an address they
-- chose**. Shipping the sender without the ceiling would be shipping the abuse.
-- FUTURENORMA §4 Step 6 makes the ladder a gate item for exactly that reason.
--
-- The reason invitations and owner claims are here rather than with billing:
-- PATHWAYS §10.7 5A.7 forbids automatic account merging, so an identity that
-- matches an address is *evidence for a claim flow*, never permission to sign
-- in. Without a claim table there is no such flow, and the only remaining way
-- to admit a first user would be the silent match that rule prohibits.

-- ---------------------------------------------------------------------------
-- users — a name to show, and when they last signed in
-- ---------------------------------------------------------------------------
--
-- `display_name` exists because of a settled policy: the run report header will
-- say "generated by <name>" in both owner and share views, and it shows a
-- display name and **never an email address** (PATHWAYS Pathway 5). A share link
-- goes to people outside the organization; leaking a colleague's address into
-- one would be a privacy incident caused by a byline.
ALTER TABLE users ADD COLUMN display_name  TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN last_login_at TIMESTAMPTZ;

-- ---------------------------------------------------------------------------
-- login_identities — one row per way a user can sign in
-- ---------------------------------------------------------------------------
--
-- Separate from `users` because one person may hold both: a developer who signs
-- in with GitHub today and clicks a magic link on their phone tomorrow is one
-- user, one seat, one set of memberships. Storing `github_id` on `users` (001
-- has such a column) cannot express that, and a second column per provider is
-- the shape that has to be migrated every time a provider is added.
--
-- `subject` is what the provider calls the account:
--
--   github — the numeric account id, **not** the login name. A GitHub username
--            can be changed and then claimed by somebody else; the numeric id
--            cannot. Keying on the name would let a renamed account be
--            impersonated by whoever took the name.
--   email  — the normalised address.
--
-- The primary key is what makes an identity unforgeable at the data layer: two
-- users cannot both claim one GitHub account.
CREATE TABLE login_identities (
  provider     TEXT NOT NULL CHECK (provider IN ('github', 'email')),
  subject      TEXT NOT NULL,
  user_id      TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_used_at TIMESTAMPTZ,
  PRIMARY KEY (provider, subject)
);
CREATE INDEX login_identities_user ON login_identities (user_id);

-- ---------------------------------------------------------------------------
-- sessions — the cookie, server-side
-- ---------------------------------------------------------------------------
--
-- **Not a JWT.** A signed token that carries its own claims cannot be withdrawn
-- before it expires: revoking a compromised session, removing someone from an
-- organization, or deleting an account would all leave a working credential in
-- somebody's browser until its clock ran out. A row that is read on every
-- request can be revoked in one statement — the same property `api_keys` has,
-- and for the same reason (`apiKeys.ts` says so).
--
-- The cookie carries a random token; only its sha256 is stored, so a database
-- dump does not hand over live sessions. Same treatment as `api_keys.key_hash`
-- and `share_links.token_hash`.
--
-- `ip_hash` and `user_agent` are for the "your sessions" list and for
-- investigating a suspicious sign-in. The address is hashed rather than stored:
-- PATHWAYS §10.7 5A.8 requires the account page to list sessions **without
-- storing or displaying raw IP addresses**, and what the list actually needs is
-- "the same device as before, or a different one", which a hash answers.
--
-- Three timestamps, three different jobs (§10.7 5A.8's launch defaults):
--
--   expires_at          absolute lifetime, 90 days. Renewal never moves it.
--   last_seen_at        idle cutoff, 30 days. Moved as the session is used.
--   reauthenticated_at  the last time this person *proved* who they are, which
--                       is what "recent authentication" is measured against for
--                       a destructive action. It starts equal to created_at and
--                       is not moved by ordinary use — otherwise every page view
--                       would refresh the proof and the requirement would mean
--                       nothing.
--
-- `rotated_at` records token rotation. Rotation replaces `token_hash` in place,
-- so the session keeps its identity, its place in the account's session list,
-- and its absolute expiry, while the bearer value in the browser changes.
CREATE TABLE sessions (
  id                 TEXT PRIMARY KEY,
  user_id            TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash         TEXT NOT NULL UNIQUE,
  method             TEXT NOT NULL CHECK (method IN ('github', 'email')),
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  reauthenticated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  rotated_at         TIMESTAMPTZ,
  expires_at         TIMESTAMPTZ NOT NULL,
  revoked_at         TIMESTAMPTZ,
  revoked_reason     TEXT NOT NULL DEFAULT '',
  ip_hash            TEXT NOT NULL DEFAULT '',
  user_agent         TEXT NOT NULL DEFAULT ''
);
CREATE INDEX sessions_user ON sessions (user_id, created_at DESC);
-- The sweep reads "what has expired"; the live list reads "what has not".
CREATE INDEX sessions_expiry ON sessions (expires_at);

-- ---------------------------------------------------------------------------
-- login_tokens — one magic link
-- ---------------------------------------------------------------------------
--
-- Hashed, so the row cannot be read out of a backup and used. Short-lived, so a
-- link left in an inbox stops working. Single-use, enforced by a conditional
-- UPDATE against `consumed_at` rather than by a read-then-write, so two
-- simultaneous clicks on the same link cannot both mint a session.
--
-- **The address is stored in plaintext here and nowhere else in this file.** It
-- has to be: the row is what says who the link belongs to. Everything else that
-- counts addresses — the throttle below — stores a keyed hash instead, because
-- counting does not need to know the address and a counter table should not
-- accumulate a list of everyone who ever tried to sign in.
--
-- `consumed_by_session` records which session a link produced, so "this link was
-- used, and here is what it opened" is answerable during an incident.
CREATE TABLE login_tokens (
  id                  TEXT PRIMARY KEY,
  email               TEXT NOT NULL,
  token_hash          TEXT NOT NULL UNIQUE,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at          TIMESTAMPTZ NOT NULL,
  consumed_at         TIMESTAMPTZ,
  consumed_by_session TEXT REFERENCES sessions(id) ON DELETE SET NULL,
  ip_hash             TEXT NOT NULL DEFAULT ''
);
CREATE INDEX login_tokens_email ON login_tokens (email, created_at DESC);
CREATE INDEX login_tokens_expiry ON login_tokens (expires_at);

-- ---------------------------------------------------------------------------
-- orgs.owner_user_id — the ownership invariant
-- ---------------------------------------------------------------------------
--
-- PATHWAYS §10.7 5A.5: "An organization has exactly one owner at a time. The
-- owner is also an `admin` membership, but ownership is a separate invariant
-- from the role so billing responsibility and owner transfer are unambiguous."
--
-- **Why a column and not just a fourth role.** Two questions get confused
-- otherwise. "Who may invite people?" is a role — several people can hold it.
-- "Who is responsible for this subscription, and who may delete the tenant?" is
-- an invariant — exactly one person, always, and transferring it is a single
-- transactional act with two parties. A role column cannot express "exactly
-- one", so it would be enforced by convention, which is to say not enforced.
--
-- **Nullable, deliberately.** An organization exists between the payment
-- webhook and the moment its purchaser first signs in — §10.7 5A.5 calls that
-- state "unclaimed", requires that it have no human console access, and makes
-- it visible to the operator console. A NOT NULL column would force the webhook
-- to invent a user, which is exactly the silent account creation 5A.7 forbids.
--
-- `ON DELETE RESTRICT`: deleting a user who still owns an organization must
-- fail loudly. Personal deletion is not organization deletion (§5), and a
-- cascade here would quietly orphan a paying tenant.
ALTER TABLE orgs ADD COLUMN owner_user_id TEXT REFERENCES users(id) ON DELETE RESTRICT;
CREATE INDEX orgs_owner ON orgs (owner_user_id);

-- ---------------------------------------------------------------------------
-- invitations — the only way a person joins an existing organization
-- ---------------------------------------------------------------------------
--
-- §10.7 5A.6's state machine, enforced by the column rather than described in a
-- comment: pending → accepted | revoked | expired.
--
-- **Hashed, single-use, short-lived** — the same three properties as a magic
-- link, for the same reason: the link in the mail *is* the credential, and this
-- one grants access to somebody else's data rather than only to your own.
--
-- **One live invitation per address per organization**, enforced by a partial
-- unique index. Resending revokes the previous row and inserts a replacement,
-- so there is never more than one working link — otherwise revoking an invite
-- would leave an older link alive and nobody would know.
--
-- `role` cannot be `owner`: ownership is transferred, never invited (5A.5).
CREATE TABLE invitations (
  id            TEXT PRIMARY KEY,
  org_id        TEXT NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  email         TEXT NOT NULL,
  role          TEXT NOT NULL CHECK (role IN ('admin', 'member', 'designer')),
  token_hash    TEXT NOT NULL UNIQUE,
  state         TEXT NOT NULL DEFAULT 'pending' CHECK (state IN ('pending', 'accepted', 'revoked', 'expired')),
  invited_by    TEXT REFERENCES users(id) ON DELETE SET NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at    TIMESTAMPTZ NOT NULL,
  resolved_at   TIMESTAMPTZ,
  accepted_user TEXT REFERENCES users(id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX invitations_one_live ON invitations (org_id, email) WHERE state = 'pending';
CREATE INDEX invitations_by_email ON invitations (email) WHERE state = 'pending';
CREATE INDEX invitations_by_org ON invitations (org_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- owner_claims — the only way an organization gets its first human
-- ---------------------------------------------------------------------------
--
-- §10.7 5A.5: the purchase webhook creates the organization and a **pending
-- owner claim tied to the checkout identity**; the purchaser then authenticates
-- and the claim is consumed atomically.
--
-- **Why this is not just an invitation with role 'owner'.** An invitation is
-- sent by an admin of an organization that already has one. A claim is created
-- by a machine for an organization that has nobody, and it carries the
-- ownership invariant rather than a role. Keeping them apart means the
-- invitation path can never mint an owner, which is 5A.6's rule.
--
-- **No token.** 5A.5: "do not put a raw email or claim authority in a URL". The
-- claim is consumed by *authenticating as the checkout address* — a magic link
-- to that address, or a GitHub account whose **verified** email matches it — so
-- the credential is the ordinary sign-in, and there is no second bearer secret
-- to leak, forward, or find in a mail archive.
--
-- `checkout_reference` is the processor's own customer/subscription id, and it
-- is UNIQUE: a retried webhook finds the row it already wrote instead of
-- creating a second organization (5A.5, first rule).
CREATE TABLE owner_claims (
  id                 TEXT PRIMARY KEY,
  org_id             TEXT NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  email              TEXT NOT NULL,
  checkout_reference TEXT NOT NULL UNIQUE,
  state              TEXT NOT NULL DEFAULT 'pending' CHECK (state IN ('pending', 'claimed', 'expired', 'cancelled')),
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at         TIMESTAMPTZ,
  claimed_at         TIMESTAMPTZ,
  claimed_user       TEXT REFERENCES users(id) ON DELETE SET NULL
);
-- One organization cannot have two pending claims, or two devices could each
-- create an owner.
CREATE UNIQUE INDEX owner_claims_one_pending ON owner_claims (org_id) WHERE state = 'pending';
CREATE INDEX owner_claims_by_email ON owner_claims (email) WHERE state = 'pending';

-- ---------------------------------------------------------------------------
-- auth_throttle — every pre-authentication ceiling, in the database
-- ---------------------------------------------------------------------------
--
-- Same argument as `rate_limit_windows` (migration 008) and the same shape, and
-- a separate table for one hard reason: that table's `org_id` is `NOT NULL` with
-- a foreign key. Everything counted here happens **before** anyone is
-- authenticated, so there is no organization to attribute it to. Widening 008's
-- column would weaken a constraint that is doing real work there.
--
-- Why not the in-process bucket in `web/lib/clientRate.ts`: it is a Map in one
-- serverless instance, and it says so itself. That is acceptable for slowing a
-- form down. It is not acceptable for a global daily ceiling on outbound mail,
-- because the platform decides how many instances exist and each one would get
-- its own private budget.
--
-- `subject` is a keyed hash for anything derived from a person — an address, an
-- IP, a subnet. Never the raw value. The counter needs to tell subjects apart,
-- which a hash does; it does not need to name them, and a table that named them
-- would be a log of who tried to sign in and from where, kept for as long as
-- nobody swept it.
--
-- `window_seconds` is derived from the scope and stored anyway, so an operator
-- reading the table can see what a row means without opening the source.
CREATE TABLE auth_throttle (
  scope          TEXT NOT NULL,
  subject        TEXT NOT NULL,
  window_start   TIMESTAMPTZ NOT NULL,
  window_seconds INTEGER NOT NULL CHECK (window_seconds > 0),
  used           INTEGER NOT NULL DEFAULT 0 CHECK (used >= 0),
  rejected       INTEGER NOT NULL DEFAULT 0 CHECK (rejected >= 0),
  PRIMARY KEY (scope, subject, window_start)
);
CREATE INDEX auth_throttle_recent ON auth_throttle (window_start DESC);

-- ---------------------------------------------------------------------------
-- auth_events — the redacted audit log for authentication
-- ---------------------------------------------------------------------------
--
-- PATHWAYS "Security and abuse-resistance baseline" item 7 asks for redacted
-- structured audit logs covering authentication, and the security release gate
-- records the audit log as outstanding. This is the authentication half.
--
-- Redacted by construction: `subject_hash` is the same keyed hash the throttle
-- uses, so an event can be tied to other events from the same address or
-- machine without the log holding either. Nothing here carries a token, a token
-- hash, or a password.
--
-- `user_id` is nullable and `ON DELETE SET NULL`: most interesting events happen
-- before anyone is identified, and an account deletion must not erase the record
-- that something happened.
-- `org_id` and `actor_user_id` are here because §10.7 5A.11 and 5A.12 require
-- every destructive auth and organization action to be audited — an invitation
-- revoked, a member removed, a role changed, ownership transferred. Those have
-- two people in them: the person acted upon (`user_id`) and the admin who
-- acted (`actor_user_id`). One column could not hold both, and "who did this"
-- is the first question asked.
CREATE TABLE auth_events (
  id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  kind          TEXT NOT NULL,
  outcome       TEXT NOT NULL CHECK (outcome IN ('allowed', 'refused', 'failed')),
  reason        TEXT NOT NULL DEFAULT '',
  subject_hash  TEXT NOT NULL DEFAULT '',
  ip_hash       TEXT NOT NULL DEFAULT '',
  user_id       TEXT REFERENCES users(id) ON DELETE SET NULL,
  actor_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  org_id        TEXT REFERENCES orgs(id) ON DELETE SET NULL,
  session_id    TEXT
);
CREATE INDEX auth_events_recent ON auth_events (at DESC);
CREATE INDEX auth_events_subject ON auth_events (subject_hash, at DESC);
CREATE INDEX auth_events_org ON auth_events (org_id, at DESC);
