#!/usr/bin/env node
//
// Generates `web/lib/legal.generated.ts` — the publishable legal documents,
// embedded as strings.
//
// **Why generated rather than retyped as TSX.** `docs/legal/*.md` is the source
// of truth for what we have committed to in writing. A hand-converted copy in
// `web/app` would be a second version of a legal document, and the two would
// drift the first time a clause changed — with the published one, the one
// people actually rely on, being the copy nobody remembered to update.
//
// **Why embedded rather than read at runtime.** The same reason
// `embed-migrations.mjs` exists: a path computed at runtime resolves
// differently inside a Vercel function bundle, and the live site fails while
// every local build stays green. See FinishedSPEC §4g.
//
// What gets published is the allowlist in `legal-manifest.mjs`, never the
// directory listing — see the reasoning there.

import { readFile, writeFile, readdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { PUBLISHED } from "./legal-manifest.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const LEGAL = path.join(ROOT, "docs", "legal");
const OUT = path.join(ROOT, "web", "lib", "legal.generated.ts");

const onDisk = new Set((await readdir(LEGAL)).filter((f) => f.endsWith(".md")));

const docs = [];
for (const entry of PUBLISHED) {
  if (!onDisk.has(entry.file)) {
    // Loud, not silent. An empty legal section on a published site is worse
    // than a failed build.
    throw new Error(`embed-legal: ${entry.file} is missing from docs/legal/`);
  }
  const markdown = await readFile(path.join(LEGAL, entry.file), "utf-8");
  docs.push(
    `  {\n` +
      `    slug: ${JSON.stringify(entry.slug)},\n` +
      `    file: ${JSON.stringify(entry.file)},\n` +
      `    title: ${JSON.stringify(entry.title)},\n` +
      `    summary: ${JSON.stringify(entry.summary)},\n` +
      `    markdown: ${JSON.stringify(markdown)},\n` +
      `  },`
  );
}

const source = `// GENERATED by scripts/embed-legal.mjs — do not edit.
//
// Source of truth: docs/legal/*.md. Regenerated by \`npm run build\`.

export interface LegalDocument {
  slug: string;
  file: string;
  title: string;
  summary: string;
  markdown: string;
}

export const LEGAL_DOCUMENTS: LegalDocument[] = [
${docs.join("\n")}
];
`;

await writeFile(OUT, source, "utf-8");
console.log(`embed-legal: ${docs.length} document(s) → web/lib/legal.generated.ts`);
